//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FrameSyn_Network_NetworkWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(FrameSyn.Network.Network), typeof(System.Object));
		L.RegFunction("OnFrameStep", OnFrameStep);
		L.RegFunction("New", _CreateFrameSyn_Network_Network);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateFrameSyn_Network_Network(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				FrameSyn.Network.Network obj = new FrameSyn.Network.Network();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: FrameSyn.Network.Network.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnFrameStep(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 4 && TypeChecker.CheckTypes(L, 1, typeof(int), typeof(int), typeof(int[]), typeof(UnityEngine.Vector2[])))
			{
				int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 2);
				int[] arg2 = ToLua.CheckNumberArray<int>(L, 3);
				UnityEngine.Vector2[] arg3 = ToLua.CheckObjectArray<UnityEngine.Vector2>(L, 4);
				FrameSyn.Network.Network.OnFrameStep(arg0, arg1, arg2, arg3);
				return 0;
			}
			else if (count == 7 && TypeChecker.CheckTypes(L, 1, typeof(int), typeof(int), typeof(int[]), typeof(float[]), typeof(float[]), typeof(bool[]), typeof(bool[])))
			{
				int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 2);
				int[] arg2 = ToLua.CheckNumberArray<int>(L, 3);
				float[] arg3 = ToLua.CheckNumberArray<float>(L, 4);
				float[] arg4 = ToLua.CheckNumberArray<float>(L, 5);
				bool[] arg5 = ToLua.CheckBoolArray(L, 6);
				bool[] arg6 = ToLua.CheckBoolArray(L, 7);
				FrameSyn.Network.Network.OnFrameStep(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: FrameSyn.Network.Network.OnFrameStep");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

