//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FrameSyn_Network_NetworkWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(FrameSyn.Network.Network), typeof(System.Object));
		L.RegFunction("OnOperationClick", OnOperationClick);
        L.RegFunction("OnFrameStep", OnFrameStep);
		L.RegFunction("New", _CreateFrameSyn_Network_Network);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateFrameSyn_Network_Network(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				FrameSyn.Network.Network obj = new FrameSyn.Network.Network();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: FrameSyn.Network.Network.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnOperationClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg2 = (int)LuaDLL.luaL_checknumber(L, 3);
			FrameSyn.Network.Network.OnOperationClick(arg0, arg1, arg2);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

    [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
    static int OnFrameStep(IntPtr L)
    {
        try
        {
            ToLua.CheckArgsCount(L, 1);
            int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
            FrameSyn.Network.Network.OnFrameStep(arg0);
            return 0;
        }
        catch (Exception e)
        {
            return LuaDLL.toluaL_exception(L, e);
        }
    }
}

